# ===========================================
# 隅烬主题配置文件
# ===========================================

# -------------------------------------------
# 站点信息设置
# -------------------------------------------
site:
  title: 隅烬主题                  # 站点标题
  subtitle: 在荒寂处黯燃             # 站点副标题
  description: 简洁美观的Hexo主题     # 站点描述
  keywords: Hexo,主题,隅烬           # 站点关键词
  author: TZ-XIAOO                  # 作者
  language: zh-CN                   # 语言
  timezone: Asia/Shanghai           # 时区

# -------------------------------------------
# 导航栏设置
# -------------------------------------------
navbar:
  # Logo设置
  logo:
    enabled: true                  # 是否显示Logo
    width: 40                      # Logo宽度
    height: 40                     # Logo高度
    
  # 站点标题设置
  title:
    main: 隅烬                     # 主标题
    sub: 在荒寂处黯燃               # 副标题
    
  # 导航链接
  menu:
    - name: OvO                    # 首页
      url: /
    - name: 木林森                  # mulinsen页面
      url: /mulinsen/
    - name: 逼逼叨                  # bbd页面
      url: /bbd/
    - name: 那远方                  # nayuanfang页面
      url: /nayuanfang/
    - name: 碎碎念                  # about页面
      url: /about/
      
  # 搜索按钮
  search:
    enabled: true                 # 是否启用搜索按钮

# -------------------------------------------
# 那远方页面配置
# -------------------------------------------
nayuanfang:
  title: 那远方                    # 页面标题
  subtitle: 美景尽收眼底            # 页面副标题
  description: 这里展示各种美景相册  # 页面描述
  albums_per_page: 6              # 每页显示相册数
  
  # 相册详情页配置
  album_detail:
    show_back_link: true          # 是否显示返回链接
    photo_style: masonry          # 照片展示样式: masonry(瀑布流), grid(网格), list(列表)

# -------------------------------------------
# 逼逼叨页面配置
# -------------------------------------------
bbd:
  title: 逼逼叨                    # 页面标题
  subtitle: 人不能总憋着，要吐槽，狠狠吐槽  # 页面副标题
  description: 时光轴形式的碎碎念    # 页面描述

# -------------------------------------------
# 木林森页面配置
# -------------------------------------------
mulinsen:
  title: 木林森                    # 页面标题
  subtitle: 木林森的碎碎念          # 页面副标题

# -------------------------------------------
# 首页配置
# -------------------------------------------
index:
  posts_per_page: 9              # 首页每页文章数

# -------------------------------------------
# 文章配置
# -------------------------------------------
post:
  wordcount: true                 # 是否显示文章字数统计
  min2read: true                  # 是否显示阅读时长
  copyright:                      # 文章版权信息
    enabled: true
    author: TZ-XIAOO
    license: CC BY-NC-SA 4.0
    license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# -------------------------------------------
# 页脚配置
# -------------------------------------------
footer:
  quote: ⇖且停且忘且随风 · 且行且看且从容⇗  # 页脚引言
  author: TZ-XIAOO                 # 作者信息
  copyright: © 2025 隅烬主题        # 版权信息
  powered_by: true                 # 是否显示由Hexo驱动

# -------------------------------------------
# 响应式设计配置
# -------------------------------------------
responsive:
  # 媒体查询断点
  breakpoints:
    xs: 480                       # 超小屏幕
    sm: 768                       # 小屏幕
    md: 1200                      # 中等屏幕
    lg: 1400                      # 大屏幕

# -------------------------------------------
# 样式配置
# -------------------------------------------
style:
  primary_color: "#333"           # 主色调
  secondary_color: "#666"         # 次要色调
  background_color: "#fff"        # 背景色
  link_color: "#333"              # 链接颜色
  link_hover_color: "#666"        # 链接悬停颜色